services:
  - type: web
    name: alpha-blog-kaif-404
    env: ruby
    plan: free
    region: oregon
    buildCommand: bundle install && yarn install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_MASTER_KEY
        value: {{80d763788e1378eac440206a9b776e52}}
      - key: postgresql://alpha_blog_database_user:ZbJerS1yqrpOlFisMpRKAaIhhSBFanIa@dpg-cqjkgvmehbks73ccvgb0-a/alpha_blog_database
        fromDatabase:
          name: alpha-blog-database
          property: connectionString

databases:
  - name: alpha-blog-database
    engine: postgres
    version: 16
    initialDiskSizeGB: 10
    plan: free
    region: oregon
